name: 'setup python'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v2
      with: 
        python-version: ${{inputs.python-version}}

    - run: |
        python -m pip install --upgrade pip
        pip install pytest
inputs:
  python-version:
    required: true
