name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted


    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        uses: actions/upload-artifact@v3
          with:
            file: mutiply.py
            path: ./src/

  test:
    runs-on: self-hosted
    steps:
      - name: "env repo sec"
        uses: actions/download-artifact@v3
          with: 
            file: multiply.py
        run: echo multiply.py
