name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Upload multiply.py
        uses: actions/upload-artifact@v4
        with:
          name: mul
          path: ./src/multiply.py

  test:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Download multiply.py
        uses: actions/download-artifact@v4
        with:
          name: mul

      - name: Show content
        run: cat multiply.py
