name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted


    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: .github/actions/setup-python
        with:
          python-version: '3.9'

      - name: Run tests
        run: |
          cd src
          python -m pytest addition.py


