name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted


    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        uses: actions/upload-artifact@v3
          with:
            name: mul
            path: ./src/multiply.py

  test:
    runs-on: self-hosted
    steps:
      - name: "env repo sec"
        uses: actions/download-artifact@v3
          with: 
            name: mul
      - name: "cat"
        run: cat multiply.py
