name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Upload multiply.py
        uses: actions/upload-artifact@v4
        with:
          name: mul
          path: ./src/multipl.py

  test:
    needs: build
    uses: ./github/workflows/reusable.yaml
    with:
      env: prod
    secrets:
      TOKEN: ${{ secrets.REPO_SEC }}
