name: Reusable file

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      num:
        required: true
        type: number
    secrets:
      TOKEN:
        required: true

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - run: echo "Env: ${{ inputs.env }}"

      - run: echo "Num: ${{ inputs.num }}"

      - run: echo "Secret: ${{ secrets.TOKEN }}"
