name: Reusable file
on: 
  workflow_call:
    inputs: 
      env:
        required: true
        type: string
      num:
        required: true
        type: int
    secret:
      TOKEN:
        required: true
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      run: echo "Env: ${{ inputs.env }}" 
      run: echo "num: ${{ inputs.num }}"
      run: echo "secret ${{ secret.TOKEN }}"
